name: Continuous Integration

on:
  push:
    branches: [master, v1.0]
  pull_request:
    branches: [master, v1.0]

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn install

      - name: Run test and generate coverage report
        run: yarn test --coverage --watchAll=false

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
